language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux
  - osx

notifications:
  email:
    - sunbergzach@gmail.com

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); include("docs/make.jl")'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
